### ISSUE TITLE
CodePath iOS for Designers Evening Bootcamp

### ISSUE THREAD

**Issue by sherwinm** [sherwinm/tips#1]
Please review my submission. Thanks! /cc @codepathreview

**Comment by timothy1ee** [comment]
this submission is incomplete since it doesn't have a gif walkthrough. At this point, the class is full, you should apply for the next one in May!

**Comment by sherwinm** [comment]
Hi Tim,

Sorry to hear the class is full. The walkthrough is located here: https://github.com/sherwinm/tips/blob/master/tips/walkthrough.gif

What is the application process for May? Also if there is a waitlist for the current course, please let me know.

Thanks!
Sherwin
